/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/experiments': {
		/**
		 * Get All Experiments
		 * @description Gets all experiments defined in this application.
		 */
		get: operations['experiments_api_get_all_experiments'];
		/**
		 * Create Experiment
		 * @description Creates a new experiment with the supplied payload, returns the experiment id.
		 */
		post: operations['experiments_api_create_experiment'];
	};
	'/api/v1/experiments/{experiment_id}': {
		/**
		 * Get Experiment By Id
		 * @description Get a specific experiemnt by its experiment ID.
		 */
		get: operations['experiments_api_get_experiment_by_id'];
		/**
		 * Update Experiment
		 * @description Updates the experiment with `experiment id`, using supplied payload
		 */
		put: operations['experiments_api_update_experiment'];
		/**
		 * Delete Experiment
		 * @description Deletes the experiment with a matching id.
		 */
		delete: operations['experiments_api_delete_experiment'];
	};
	'/api/v1/experiments/{experiment_id}/observations': {
		/**
		 * Get All Observations
		 * @description Gets all observations defined for provided experiment id.
		 */
		get: operations['experiments_api_get_all_observations'];
	};
	'/api/v1/experiments/{experiment_id}/observations/{observation_id}': {
		/**
		 * Get Observation By Id
		 * @description Get a specific observation by its experiment id and observation id.
		 */
		get: operations['experiments_api_get_observation_by_id'];
	};
	'/api/v1/experiments/{experiment_id}/observation': {
		/**
		 * Create Observation
		 * @description Creates a new observation with the supplied payload, returns the observation id.
		 */
		post: operations['experiments_api_create_observation'];
	};
	'/api/v1/experiments/{experiment_id}/observation/{observation_id}': {
		/**
		 * Update Observation
		 * @description Updates the observation on experiment, using supplied payload
		 */
		put: operations['experiments_api_update_observation'];
		/**
		 * Delete Observation
		 * @description Deletes the observation on provided experiment with a matching id.
		 */
		delete: operations['experiments_api_delete_observation'];
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		/** ExperimentOut */
		ExperimentOut: {
			/** Id */
			id?: number;
			/** Name */
			name: string;
			/** Description */
			description: string;
			/**
			 * Date Started
			 * Format: date
			 */
			date_started: string;
			/**
			 * Date Ended
			 * Format: date
			 */
			date_ended: string;
			/** Correct Sample */
			correct_sample: string;
		};
		/** JustId */
		JustId: {
			/** Id */
			id: number;
		};
		/** ExperimentIn */
		ExperimentIn: {
			/** Name */
			name: string;
			/** Description */
			description: string;
			/**
			 * Date Started
			 * Format: date
			 */
			date_started: string;
			/**
			 * Date Ended
			 * Format: date
			 */
			date_ended: string;
			/** Correct Sample */
			correct_sample: string;
		};
		/** Success */
		Success: {
			/** Success */
			success: boolean;
		};
		/** ObservationOut */
		ObservationOut: {
			/** Experience Level */
			experience_level: number;
			/**
			 * Chosen Sample
			 * @enum {string}
			 */
			chosen_sample: 'A' | 'B' | 'C';
			/**
			 * Observation Date
			 * Format: date-time
			 */
			observation_date: string;
			/** Id */
			id: number;
			/** Experiment */
			experiment: number;
		};
		/** ObservationIn */
		ObservationIn: {
			/** Experience Level */
			experience_level: number;
			/**
			 * Chosen Sample
			 * @enum {string}
			 */
			chosen_sample: 'A' | 'B' | 'C';
			/**
			 * Observation Date
			 * Format: date-time
			 */
			observation_date: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
	/**
	 * Get All Experiments
	 * @description Gets all experiments defined in this application.
	 */
	experiments_api_get_all_experiments: {
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['ExperimentOut'][];
				};
			};
		};
	};
	/**
	 * Create Experiment
	 * @description Creates a new experiment with the supplied payload, returns the experiment id.
	 */
	experiments_api_create_experiment: {
		requestBody: {
			content: {
				'application/json': components['schemas']['ExperimentIn'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['JustId'];
				};
			};
		};
	};
	/**
	 * Get Experiment By Id
	 * @description Get a specific experiemnt by its experiment ID.
	 */
	experiments_api_get_experiment_by_id: {
		parameters: {
			path: {
				experiment_id: number;
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['ExperimentOut'];
				};
			};
		};
	};
	/**
	 * Update Experiment
	 * @description Updates the experiment with `experiment id`, using supplied payload
	 */
	experiments_api_update_experiment: {
		parameters: {
			path: {
				experiment_id: number;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ExperimentIn'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['Success'];
				};
			};
		};
	};
	/**
	 * Delete Experiment
	 * @description Deletes the experiment with a matching id.
	 */
	experiments_api_delete_experiment: {
		parameters: {
			path: {
				experiment_id: number;
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['Success'];
				};
			};
		};
	};
	/**
	 * Get All Observations
	 * @description Gets all observations defined for provided experiment id.
	 */
	experiments_api_get_all_observations: {
		parameters: {
			path: {
				experiment_id: number;
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['ObservationOut'][];
				};
			};
		};
	};
	/**
	 * Get Observation By Id
	 * @description Get a specific observation by its experiment id and observation id.
	 */
	experiments_api_get_observation_by_id: {
		parameters: {
			path: {
				experiment_id: number;
				observation_id: number;
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['ObservationOut'];
				};
			};
		};
	};
	/**
	 * Create Observation
	 * @description Creates a new observation with the supplied payload, returns the observation id.
	 */
	experiments_api_create_observation: {
		parameters: {
			path: {
				experiment_id: number;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ObservationIn'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['JustId'];
				};
			};
		};
	};
	/**
	 * Update Observation
	 * @description Updates the observation on experiment, using supplied payload
	 */
	experiments_api_update_observation: {
		parameters: {
			path: {
				experiment_id: number;
				observation_id: number;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ObservationIn'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['Success'];
				};
			};
		};
	};
	/**
	 * Delete Observation
	 * @description Deletes the observation on provided experiment with a matching id.
	 */
	experiments_api_delete_observation: {
		parameters: {
			path: {
				experiment_id: number;
				observation_id: number;
			};
		};
		responses: {
			/** @description OK */
			200: {
				content: {
					'application/json': components['schemas']['Success'];
				};
			};
		};
	};
}
